# -*- coding: utf-8 -*-
"""
Модуль для работы с Anki через AnkiConnect API.
"""
import os
import requests
import base64
from typing import List, Optional, Dict, Any, Union
from core.logger import debug_log

# Константы
MODEL_NAME = "YouTube"
ANKI_CONNECT_URL = "http://localhost:8765"
DEFAULT_TIMEOUT = 5


class AnkiAPI:
    """Класс для работы с Anki через AnkiConnect"""
    
    def __init__(self, url: str = ANKI_CONNECT_URL):
        self.url = url
        self.model_name = MODEL_NAME
        self.session = requests.Session()
    
    def _request(self, action: str, params: Dict = None, timeout: float = DEFAULT_TIMEOUT) -> Any:
        """
        Отправляет запрос к AnkiConnect.
        
        Args:
            action: Название действия API
            params: Параметры запроса
            timeout: Таймаут в секундах
            
        Returns:
            Результат запроса
            
        Raises:
            Exception: При ошибке соединения или API
        """
        payload = {"action": action, "version": 6}
        if params:
            payload["params"] = params
        
        try:
            # Используем сессию для переиспользования соединения
            response = self.session.post(self.url, json=payload, timeout=timeout)
            result = response.json()
            
            if result.get("error"):
                raise Exception(result["error"])
            
            return result.get("result")
        except requests.exceptions.ConnectionError:
            raise Exception("ANKI_CONNECT_ERROR")
        except requests.exceptions.Timeout:
            raise Exception("ANKI_TIMEOUT_ERROR")
    
    def is_available(self) -> bool:
        """Проверяет доступность AnkiConnect"""
        try:
            self._request("version", timeout=0.5)
            return True
        except Exception:
            return False
    
    # === Модели ===
    
    def get_model_names(self) -> List[str]:
        """Получает список имен моделей"""
        return self._request("modelNames", timeout=1) or []
    
    def model_exists(self, model_name: str = None) -> bool:
        """Проверяет существование модели (регистронезависимо)"""
        name = (model_name or self.model_name).strip().lower()
        existing_models = [m.strip().lower() for m in self.get_model_names()]
        return name in existing_models
    
    def get_model_field_names(self, model_name: str = None) -> List[str]:
        """Получает список полей модели"""
        name = model_name or self.model_name
        try:
            return self._request("modelFieldNames", {"modelName": name}, timeout=1) or []
        except Exception:
            return []

    def setup_model(self) -> bool:
        """
        Создает тип записи 'YouTube' с полями и CSS стилями.
        Если модель уже существует, проверяет наличие необходимых полей.
        
        Returns:
            True если модель создана или уже существует
        """
        required_fields = ["Phrase", "Translation", "Context", "Sound"]
        css = """
        .card {
            font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            font-size: 20px;
            text-align: center;
        }
        .phrase {
            font-size: 32px;
            font-weight: bold;
            margin-bottom: 20px;
            color: #ffffff;
        }
        .translation {
            font-size: 24px;
            margin-top: 20px;
        }
        .context {
            font-size: 16px;
            font-style: italic;
            margin-top: 15px;
            text-align: left;
            display: inline-block;
            max-width: 90%;
            background-color: #333333;
            color: #ffffff;
            padding: 12px;
            border-radius: 8px;
            border: 1px solid #444;
        }
        .sound { margin-top: 10px; }
        """
        
        card_templates = [
            {
                "name": "Card 1",
                "Front": '<div class="phrase">{{Phrase}}</div><div class="sound">{{Sound}}</div>',
                "Back": '<div class="phrase">{{Phrase}}</div><hr id="answer"><div class="translation">{{Translation}}</div><div class="context">{{Context}}<div class="watermark" style="font-size: 10px; margin-top: 10px; text-align: right;"><a href="https://LanguageSage.github.io/Anki-card-andder/" style="color: #666; text-decoration: none;">Generated by Lerne Assistant</a></div></div>'
            }
        ]

        existing_models = self.get_model_names()
        existing_models_lower = [m.lower().strip() for m in existing_models]
        target_lower = self.model_name.lower().strip()

        if target_lower in existing_models_lower:
            # Находим оригинальное имя модели (которое в Anki)
            original_index = existing_models_lower.index(target_lower)
            actual_model_name = existing_models[original_index]
            self.model_name = actual_model_name # Принимаем имя из Anki
            
            # Если модель существует, проверяем поля
            current_fields = self.get_model_field_names(actual_model_name)
            
            # ВАЖНО: Если список полей пуст, хотя модель найдена — это скорее всего глюк AnkiConnect (таймаут).
            # Не пытаемся "добавлять" поля в этом случае, чтобы не сломать структуру.
            if not current_fields:
                print(f"⚠️ Не удалось получить список полей для '{self.model_name}'. Пропуск настройки полей.")
                return True
                
            missing_fields = [f for f in required_fields if f not in current_fields]
            
            if missing_fields:
                print(f"⚠️ В модели '{self.model_name}' отсутствуют поля: {missing_fields}. Попытка добавить...")
                for field in missing_fields:
                    try:
                        self._request("modelFieldAdd", {
                            "modelName": self.model_name,
                            "fieldName": field
                        })
                        print(f"✅ Поле '{field}' добавлено.")
                    except Exception as e:
                        print(f"❌ Ошибка добавления поля '{field}': {e}")
                # Если были изменения полей, то стили и шаблоны обновим ниже.
            elif target_lower in [m.lower().strip() for m in existing_models]:
                # Если поля на месте и модель не новая — не спамим обновлениями шаблонов без нужды
                # Это предотвращает временное "исчезновение" полей в интерфейсе Anki при каждом запуске
                return True
            
            # Также обновляем CSS и шаблоны на всякий случай
            try:
                self._request("updateModelStyling", {
                    "model": {
                        "name": self.model_name,
                        "css": css
                    }
                })
                self._request("updateModelTemplates", {
                    "model": {
                        "name": self.model_name,
                        "templates": {
                            "Card 1": {
                                "Front": card_templates[0]["Front"],
                                "Back": card_templates[0]["Back"]
                            }
                        }
                    }
                })
                print(f"✅ Стили и шаблоны модели '{self.model_name}' обновлены.")
            except Exception as e:
                print(f"⚠️ Не удалось обновить стили/шаблоны: {e}")
                
            return True
        
        print(f"🛠 Настройка Anki: создание типа записи '{self.model_name}'...")
        
        try:
            self._request("createModel", {
                "modelName": self.model_name,
                "inOrderFields": required_fields,
                "css": css,
                "cardTemplates": card_templates
            })
            print(f"✅ Тип записи '{self.model_name}' успешно создан!")
            return True
        except Exception as e:
            print(f"❌ Ошибка создания модели: {e}")
            return False
    
    # === Колоды ===
    
    def get_deck_names(self, with_counts: bool = True) -> Union[List[str], str]:
        """
        Получает список колод.
        
        Args:
            with_counts: Если True, добавляет количество карточек
            
        Returns:
            Список колод или "ANKI_CONNECT_ERROR"
        """
        try:
            deck_names = self._request("deckNames", timeout=0.5) or []
            
            if not with_counts:
                return sorted(deck_names)
            
            # Получаем статистику
            stats = self._request("getDeckStats", {"decks": deck_names}, timeout=1.0) or {}
            
            deck_counts = {}
            for deck_id, stat in stats.items():
                name = stat.get("name")
                count = stat.get("total_in_deck", 0)
                if name:
                    deck_counts[name] = count
            
            # Формируем список "Имя (Количество)"
            formatted = [f"{name} ({deck_counts.get(name, 0)})" for name in deck_names]
            return sorted(formatted)
            
        except Exception as e:
            if "ANKI_CONNECT_ERROR" in str(e):
                return "ANKI_CONNECT_ERROR"
            print(f"Ошибка получения колод: {e}")
            return []
    
    def create_deck(self, deck_name: str) -> bool:
        """Создает новую колоду"""
        if not deck_name or not deck_name.strip():
            return False
        
        try:
            self._request("createDeck", {"deck": deck_name.strip()}, timeout=8)
            return True
        except Exception as e:
            print(f"❌ Ошибка создания колоды: {e}")
            return False
    
    @staticmethod
    def clean_deck_name(display_name: str) -> str:
        """
        Убирает суффикс с количеством карточек.
        Пример: "Deutsch (150)" -> "Deutsch"
        """
        if not display_name:
            return ""
        
        last_open_paren = display_name.rfind(" (")
        if last_open_paren != -1 and display_name.endswith(")"):
            content = display_name[last_open_paren+2:-1]
            if content.isdigit():
                return display_name[:last_open_paren]
        return display_name
    
    # === Заметки ===
    
    def find_notes(self, phrase: str) -> List[int]:
        """Ищет ID заметок с такой же фразой"""
        try:
            escaped_phrase = phrase.replace('"', '\\"')
            query = f'Phrase:"{escaped_phrase}"'
            return self._request("findNotes", {"query": query}, timeout=3) or []
        except Exception as e:
            print(f"⚠️ Ошибка поиска заметок: {e}")
            return []
    
    def delete_notes(self, note_ids: List[int]) -> bool:
        """Удаляет заметки по их ID"""
        if not note_ids:
            return True
        
        try:
            self._request("deleteNotes", {"notes": note_ids})
            return True
        except Exception as e:
            print(f"❌ Ошибка удаления заметок: {e}")
            return False
    
    def add_note(self, phrase: str, translation: str, context: str, 
                 deck_name: str, audio_path: str = None, allow_duplicate: bool = False) -> bool:
        """
        Добавляет заметку в Anki.
        
        Args:
            phrase: Немецкая фраза
            translation: Перевод
            context: Контекст
            deck_name: Имя колоды
            audio_path: Путь к аудиофайлу (опционально)
            allow_duplicate: Разрешить добавление дубликатов (по умолчанию False)
            
        Returns:
            True при успехе
        """
        clean_name = self.clean_deck_name(deck_name)
        
        def _log(msg):
            debug_log(msg, prefix="[API]")

        note = {
            "deckName": clean_name,
            "modelName": self.model_name,
            "fields": {
                "Phrase": phrase.replace('\n', '<br>'),
                "Translation": translation.replace('\n', '<br>'),
                "Context": context.replace('\n', '<br>'),
                "Sound": ""  # Explicitly include the Sound field
            },
            "options": {
                "allowDuplicate": allow_duplicate
            },
            "tags": ["youtube", "german", "local-ai"]
        }
        
        if audio_path and os.path.exists(audio_path):
            try:
                # По просьбе пользователя убрана проверка на пустой файл (размер > 0).
                # Это позволит видеть текст ошибки AnkiConnect прямо в поле для отладки.
                with open(audio_path, "rb") as f:
                    audio_data = base64.b64encode(f.read()).decode("utf-8")
                
                if not audio_data:
                    _log(f"⚠️ Ошибка кодирования аудио: пустые данные.")
                else:
                    # Check for correct field name casing
                    actual_fields = self.get_model_field_names()
                    _log(f"📋 Actual fields in model: {actual_fields}")
                    target_field = "Sound"
                    
                    if actual_fields:
                        if "Sound" not in actual_fields:
                            # Try to find a case-insensitive match or fallback to the first likely field
                            for gf in actual_fields:
                                if gf.lower() == "sound" or gf.lower() == "audio":
                                    target_field = gf
                                    _log(f"🔍 Found matching field: '{target_field}'")
                                    break
                    
                    _log(f"🔊 Attaching audio to field '{target_field}'. File: {os.path.basename(audio_path)}")
                    
                    note["audio"] = [{
                        "data": audio_data,
                        "filename": os.path.basename(audio_path),
                        "fields": [target_field]
                    }]
            except Exception as e:
                _log(f"⚠️ Ошибка обработки аудио файла: {e}")
        
        result = self._request("addNote", {"note": note})
        _log(f"🎯 Anki response: {result}")
        return True


# Глобальный экземпляр API
anki_api = AnkiAPI()
